import { Module } from "./Module.js";

// codegen:start {preset: custom, source: ../tools/codegen-module-index.cjs, export: moduleCodegen}
/// This file is generated by tools/codegen-module-index.cjs. Run `pnpm lint:codegen` to update it.
import Example from "./modules/Example.js";
import ForumPinner from "./modules/ForumPinner.js";
import Info from "./modules/Info.js";
import Ping from "./modules/Ping.js";
import System from "./modules/System.js";
const modules = {
  Example,
  ForumPinner,
  Info,
  Ping,
  System,
} as const satisfies Record<string, typeof Module>;
// codegen:end

export type ModuleName = keyof typeof modules;
export default modules;
